import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import { PublicEnvScript } from "next-runtime-env";
import TanstackQueryProvider from "@/components/provider/tanstack-query-provider";
import { Toaster } from "sonner";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai", "latin"],
});

export const metadata: Metadata = {
  title: "Member Please Scan",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                const theme = localStorage.getItem('theme');
                if (theme === 'dark') {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              } catch (e) {}
            `,
          }}
        />
        <PublicEnvScript />
      </head>
      <body className={`${notoSansThai.variable} antialiased`}>
        <TanstackQueryProvider>
          <Toaster expand richColors position="top-center" />
          {children}
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
