import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import { PublicEnvScript } from "next-runtime-env";
import TanstackQueryProvider from "@/components/provider/tanstack-query-provider";
import { Toaster } from "sonner";
import TranslationsProvider from "@/components/provider/translations-provider";
import { cookies } from "next/headers";
import initTranslations, { i18nNamespaces } from "@/lib/i18n/i18n";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai", "latin"],
});

export const metadata: Metadata = {
  title: "Member Please Scan",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = await cookies();
  const locals = cookiesStore.get("i18next")?.value || "th";
  const { resources } = await initTranslations(locals, i18nNamespaces);

  return (
    <html lang="th" suppressHydrationWarning className="dark">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                const theme = localStorage.getItem('theme');
                if (theme === 'dark') {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              } catch (e) {}
            `,
          }}
        />
        <PublicEnvScript />
      </head>
      <body className={`${notoSansThai.variable} antialiased`}>
        <TanstackQueryProvider>
          <TranslationsProvider
            namespaces={i18nNamespaces}
            locale={locals}
            resources={resources}
          >
            <Toaster expand richColors position="top-center" />
            {children}
          </TranslationsProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
